QL_DatVeXe/QL_DatVeXe/Controllers/VeXeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QL_DatVeXe.Models;

namespace QL_DatVeXe.Controllers
{
    public class VeXeController : Controller
    {
        QL_DATVEXEDataContext db = new QL_DATVEXEDataContext();
        // GET: VeXe
        public ActionResult ShowAllVeXe(int? page)
        {
            Session["TB"] = "";

            var user = Session["user"] as string;
            if (string.IsNullOrEmpty(user))
                Session["user"] = string.Empty;

            Session["favorite"] = db.VEXEYEUTHICHes.Where(t => t.KHACHHANG.TENKH == user).Count();

            int itemsPerPage = 9;
            int pageNumber = (page ?? 1);

            var setve = db.VEXEs.OrderBy(t => t.TENVE).ToList();
            if (setve.Count > 0)
            {
                for (int i = 0; i < setve.Count; i++)
                {
                    setve[i].YEUTHICH = false;
                    db.SubmitChanges();
                }
            }

            if (!string.IsNullOrEmpty(user))
            {
                var kh = db.KHACHHANGs.SingleOrDefault(t => t.TENKH == user);
                var veyeuthich = db.VEXEYEUTHICHes.Where(t => t.MAKH == kh.MAKH).ToList();

                if (veyeuthich.Count > 0)
                {
                    for (int i = 0; i < setve.Count; i++)
                    {
                        for (int j = 0; j < veyeuthich.Count; j++)
                        {
                            if (setve[i].MAVE == veyeuthich[j].MAVE)
                            {
                                setve[i].YEUTHICH = true;
                                db.SubmitChanges();
                            }
                        }
                    }
                }
            }

            var listVeXe = db.VEXEs.OrderBy(t => t.TENVE).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            ViewBag.TotalPages = Math.Ceiling((double)db.VEXEs.Count() / itemsPerPage);
            ViewBag.CurrentPage = pageNumber;
            return View(listVeXe);
        }

        public ActionResult TimVe(int? page, string diemdon, string diemden, DateTime? ngaydi, DateTime? ngayve)
        {
            Session["TB"] = "";

            var listVeXe = new List<VEXE>();
            var user = Session["user"] as string;
            if (string.IsNullOrEmpty(user))
                Session["user"] = string.Empty;

            int itemsPerPage = 9;
            int pageNumber = (page ?? 1);

            if (diemdon == null && diemden == null && ngaydi == null && ngayve == null)
                listVeXe = db.VEXEs.OrderBy(t => t.TENVE).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();

            else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
            {
                listVeXe = db.VEXEs.OrderBy(t => t.TENVE).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (!diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDON == diemdon && t.DIEMDEN == diemden && t.NGAYDI == ngaydi && t.NGAYVE == ngayve).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (!diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDON == diemdon && t.DIEMDEN == diemden && t.NGAYDI == ngaydi).ToList();
            }
            else if (!diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDON == diemdon && t.DIEMDEN == diemden).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDEN == diemden).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (!diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDON == diemdon).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.NGAYDI == ngaydi).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve != null)
            {
                listVeXe = db.VEXEs.Where(t => t.NGAYVE == ngayve).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
            {
                listVeXe = db.VEXEs.Where(t => t.NGAYDI == ngaydi && t.NGAYVE == ngayve).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (!diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDON == diemdon && t.NGAYDI == ngaydi && t.NGAYVE == ngayve).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (!diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDON == diemdon && t.NGAYDI == ngaydi).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDEN == diemden && t.NGAYDI == ngaydi && t.NGAYVE == ngayve).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            else if (diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
            {
                listVeXe = db.VEXEs.Where(t => t.DIEMDEN == diemden && t.NGAYDI == ngaydi).Skip((pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            }
            if (listVeXe.Count == 0)
            {
                if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
                    Session["TB"] = "Bạn chưa chọn mục tiêu để tìm kiếm";
                else if (!diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
                    Session["TB"] = "Không có vé xe đi từ " + diemdon + " đến " + diemden + " ngày " + ngaydi + " - " + ngayve;
                else if (!diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
                    Session["TB"] = "Không có vé xe đi từ " + diemdon + " đến " + diemden + " ngày " + ngaydi;
                else if (!diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
                    Session["TB"] = "Không có vé xe đi từ " + diemdon + " đến " + diemden;
                else if (diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
                    Session["TB"] = "Không có vé xe đến " + diemden;
                else if (!diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve == null)
                    Session["TB"] = "Không có vé xe đi từ " + diemdon;
                else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
                    Session["TB"] = "Không có vé xe đi từ ngày " + ngaydi;
                else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi == null && ngayve != null)
                    Session["TB"] = "Không có vé xe đi về ngày " + ngayve;
                else if (diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
                    Session["TB"] = "Không có vé xe đi từ ngày " + ngaydi + " - " + ngayve;
                else if (!diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
                    Session["TB"] = "Không có vé xe đi từ " + diemdon + " ngày " + ngaydi + " - " + ngayve;
                else if (!diemdon.Equals("Chọn nơi xuất phát") && diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
                    Session["TB"] = "Không có vé xe đi từ " + diemdon + " ngày " + ngaydi;
                else if (diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve != null)
                    Session["TB"] = "Không có vé xe đến " + diemden + " ngày " + ngaydi + " - " + ngayve;
                else if (diemdon.Equals("Chọn nơi xuất phát") && !diemden.Equals("Chọn nơi đến") && ngaydi != null && ngayve == null)
                    Session["TB"] = "Không có vé xe đến " + diemden + " ngày " + ngaydi;
            }
            else
            {

QL_DatVeXe/QL_DatVeXe/Controllers/YeuThichController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QL_DatVeXe.Models;

namespace QL_DatVeXe.Controllers
{
    public class YeuThichController : Controller
    {
        QL_DATVEXEDataContext db = new QL_DATVEXEDataContext();
        // GET: YeuThich
        public ActionResult VeXeYeuThich()
        {
            var user = Session["user"] as string;
            if (string.IsNullOrEmpty(user))
                Session["user"] = string.Empty;

            Session["favorite"] = db.VEXEYEUTHICHes.Where(t => t.KHACHHANG.TENKH == user).Count();

            var setve = db.VEXEs.OrderBy(t => t.TENVE).ToList();
            if (setve.Count > 0)
            {
                for (int i = 0; i < setve.Count; i++)
                {
                    setve[i].YEUTHICH = false;
                    db.SubmitChanges();
                }
            }

            if (!string.IsNullOrEmpty(user))
            {
                var kh = db.KHACHHANGs.SingleOrDefault(t => t.TENKH == user);
                var veyeuthich = db.VEXEYEUTHICHes.Where(t => t.MAKH == kh.MAKH).ToList();

                if (veyeuthich.Count > 0)
                {
                    for (int i = 0; i < setve.Count; i++)
                    {
                        for (int j = 0; j < veyeuthich.Count; j++)
                        {
                            if (setve[i].MAVE == veyeuthich[j].MAVE)
                            {
                                setve[i].YEUTHICH = true;
                                db.SubmitChanges();
                            }
                        }
                    }
                }
            }

            var favorite = db.VEXEYEUTHICHes.Where(t => t.KHACHHANG.TENKH == user).ToList();
            if (favorite.Count == 0)
                return RedirectToAction("YeuThichRong", "YeuThich");
            return View(favorite);
        }

        public ActionResult YeuThichRong()
        {
            return View();
        }

        public ActionResult ThemVeXeYeuThich(VEXEYEUTHICH spyt, int mave)
        {
            var user = Session["user"] as string;
            if (string.IsNullOrEmpty(user))
                return RedirectToAction("DangNhap", "NguoiDung");

            var sp = db.VEXEYEUTHICHes.Where(n => n.KHACHHANG.TENKH == user).Where(m => m.MAVE == mave).ToList();
            var kh = db.KHACHHANGs.SingleOrDefault(k => k.TENKH.Equals(user));
            if (sp.Count == 0)
            {
                spyt.MAKH = kh.MAKH;
                spyt.MAVE = mave;
                db.VEXEYEUTHICHes.InsertOnSubmit(spyt);
                db.SubmitChanges();
                ViewBag.TB = "Đã thêm vé xe vào danh sách yêu thích!";
            }
            else
                ViewBag.TB = "Vé xe đã được yêu thích!";

            return RedirectToAction("VeXeYeuThich", "YeuThich");
        }

        public ActionResult XoaVeXeYeuThich(int mave)
        {
            var user = Session["user"] as string;

            VEXEYEUTHICH sp = db.VEXEYEUTHICHes.Where(n => n.KHACHHANG.TENKH == user).Where(m => m.MAVE == mave).Single();
            var favorite = db.VEXEYEUTHICHes.Where(t => t.KHACHHANG.TENKH == user).ToList();
            if (sp != null)
            {
                db.VEXEYEUTHICHes.DeleteOnSubmit(sp);
                db.SubmitChanges();
                ViewBag.TB = "Đã xóa vé xe khỏi danh sách yêu thích!";
                return RedirectToAction("VeXeYeuThich", "YeuThich");
            }
            else
                ViewBag.TB = "Xóa thất bại!";
            if(favorite.Count == 0)
                return RedirectToAction("YeuThichRong", "YeuThich");
            return RedirectToAction("VeXeYeuThich", "YeuThich");
        }
    }
}

QL_DatVeXe/QL_DatVeXe/Views/YeuThich/VeXeYeuThich.cshtml
@model IEnumerable<QL_DatVeXe.Models.VEXEYEUTHICH>

@{
    ViewBag.Title = "VeXeYeuThich";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wishlist-area pt-60 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="#">
                    <div class="table-content table-responsive mt-5">
                        <table class="table">
                            <thead>
                                <tr style="background-color:rgba(245, 199, 134, 0.53)">
                                    <th class="li-product-remove" style="color:black; font-size:16px; font-weight:bold">Xóa</th>
                                    <th class="li-product-thumbnail" style="color:black; font-size:16px; font-weight:bold">Hình Ảnh</th>
                                    <th class="cart-product-name" style="color:black; font-size:16px; font-weight:bold">Địa Điểm</th>
                                    <th class="li-product-price" style="color:black; font-size:16px; font-weight:bold">Giá Vé</th>
                                    <th class="li-product-stock-status" style="color:black; font-size:16px; font-weight:bold">Ghế Trống</th>
                                    <th class="li-product-add-cart" style="color:black; font-size:16px; font-weight:bold">add to cart</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="li-product-remove"><a href="@Url.Action("XoaVeXeYeuThich", "YeuThich", new {mave = item.MAVE})"><i class="fa fa-times"></i></a></td>
                                        <td class="li-product-thumbnail"><a href="@Url.Action("XemChiTietVeXe", "VeXe", new {mave = item.MAVE, diemden = item.VEXE.DIEMDEN})"><img src="~/Content/images/@item.VEXE.HINHANH" alt="" width="150" height="150"></a></td>
                                        <td class="li-product-name"><a style="color:black" href="@Url.Action("XemChiTietVeXe", "VeXe", new {mave = item.MAVE, diemden = item.VEXE.DIEMDEN})">@item.VEXE.DIEMDON - @item.VEXE.DIEMDEN</a></td>
                                        <td class="li-product-price" style="color:black"><span class="amount">@string.Format("{0:N0}", item.VEXE.GIAVE)&ETH;</span></td>
                                        @if (item.VEXE.CONTRONG > 0)
                                        {
                                            <td class="li-product-stock-status"><span class="in-stock">@item.VEXE.CONTRONG</span></td>
                                        }
                                        else
                                        {
                                            <td class="li-product-stock-status"><span class="out-stock">@item.VEXE.CONTRONG</span></td>

                                        }
                                        <td class="li-product-add-cart"><a href="@Url.Action("DatVe", "VeXe", new { mave = item.VEXE.MAVE })">Đặt Vé</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

QL_DatVeXe/QL_DatVeXe/Views/YeuThich/YeuThichRong.cshtml
@{
    ViewBag.Title = "YeuThichRong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row ml-150">
    <h2 class="text-warning m-5 text-ml">Không có gì trong danh sách yêu thích</h2>
    <a class="mua-them" href="/VeXe/ShowAllVeXe">Xem Thêm Vé</a>
</div>