QL_DatVeXe/QL_DatVeXe/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QL_DatVeXe.Models;

namespace QL_DatVeXe.Controllers
{
    public class NguoiDungController : Controller
    {
        QL_DATVEXEDataContext db = new QL_DATVEXEDataContext();
        // GET: NguoiDung
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(KHACHHANG kh, string fullname, string username, DateTime date, string password, string gender, string repassword, string address, string email, string phone)
        {
            if (password == repassword)
            {
                KHACHHANG check = db.KHACHHANGs.SingleOrDefault(n => n.TAIKHOAN.Equals(username));
                if (check == null)
                {
                    kh.TENKH = fullname;
                    kh.GIOITINH = gender;
                    kh.NGAYSINH = date;
                    kh.DIACHI = address;
                    kh.SDT = phone;
                    kh.TAIKHOAN = username;
                    kh.MATKHAU = password;
                    kh.EMAIL = email;
                    kh.TRANGTHAI = "Không khóa";
                    db.KHACHHANGs.InsertOnSubmit(kh);
                    db.SubmitChanges();
                    ViewBag.TB = "Đăng ký thành công!";
                }
                else
                    ViewBag.TB = "Username " +username+ " đã được sử dụng!";
            }
            else
                ViewBag.TB = "Nhập lại mật khẩu không chính xác, vui lòng nhập lại!";
            return View();
        }

        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(string username, string password)
        {
            if (!String.IsNullOrEmpty(username) && !String.IsNullOrEmpty(password))
            {
                KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.TAIKHOAN.Equals(username) && n.MATKHAU.Equals(password));
                if (kh != null)
                {
                    Session["user"] = kh.TENKH;
                    //TempData["Notification"] = "Đăng nhập thành công";
                    return RedirectToAction("ShowAllVeXe", "VeXe");
                }
                else
                {
                    ViewBag.TB = "Tài khoản hoặc mật khẩu không chính xác, vui lòng nhập lại!";
                }
            }
            return View();
        }

        public ActionResult DangXuat()
        {
            Session["user"] = string.Empty;
            return RedirectToAction("ShowAllVeXe", "VeXe");
        }
    }
}

QL_DatVeXe/QL_DatVeXe/Views/NguoiDung/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/Account.cshtml";
}

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center mb-2">
                <h2 class="heading-section">Sign Up</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8">
                <div class="login-wrap p-0">
                    @if (ViewBag.TB == "Đăng ký thành công!")
                    {
                        <h3 class="mb-4 text-center text-success font-weight-bold">@ViewBag.TB</h3>
                    }
                    else
                    {
                        <h3 class="mb-4 text-center text-danger font-weight-bold">@ViewBag.TB</h3>
                    }
                    <h3 class="mb-4 text-center">Do not have an account?</h3>
                    @using (Html.BeginForm())
                    {
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Full Name" name="fullname" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Username" name="username" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="date" class="form-control" name="date" value="2002-08-04" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password" name="password" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select class="form-control" id="genderSelect" name="gender" required>
                                        <option selected>Nam</option>
                                        <option>Nữ</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Re-Password" name="repassword" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Address" name="address" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Email Address" name="email" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Phone Number" name="phone" pattern="[0-9]+" required>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="form-control btn btn-primary submit px-3">Sign Up</button>
                        </div>
                        <p class="w-100 text-center">&mdash; Have an account? &mdash;</p>
                        <div class="form-group">
                            <button type="button" class="form-control btn btn-primary submit px-3" onclick="location.href='@Url.Action("DangNhap", "NguoiDung")'">Sign In</button>
                        </div>
                        <p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
                        <div class="social d-flex text-center">
                            <a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
                            <a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

QL_DatVeXe/QL_DatVeXe/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/Account.cshtml";
}
<section class="ftco-sectionLogin">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Sign In</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="login-wrap p-0">
                    <h3 class="mb-4 text-center text-danger font-weight-bold">@ViewBag.TB</h3>
                    <h3 class="mb-4 text-center">Have an account?</h3>
                    @using (Html.BeginForm())
                    {
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" required>
                        </div>
                        <div class="form-group">
                            <input id="password-field" type="password" class="form-control" placeholder="Password" name="password" required>
                            <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                        </div>
                        <div class="form-group d-md-flex">
                            <div class="w-50">
                                <label class="checkbox-wrap checkbox-primary">
                                    Remember me
                                    <input type="checkbox" checked>
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <div class="w-50 text-md-right">
                                <a href="#" style="color: #fff">Forgot Password</a>
                            </div>
                        </div>
                        <p class="w-100 text-center">&mdash; Do not have an account? &mdash;</p>
                        <div class="form-group">
                            <button type="button" class="form-control btn btn-primary submit px-3" onclick="location.href='@Url.Action("DangKy", "NguoiDung")'">Sign Up</button>
                        </div>
                        <p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
                        <div class="social d-flex text-center">
                            <a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
                            <a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>